apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapi
  namespace: api-servers
spec:
  selector:
    matchLabels:
      app: nodeapi   
  template:
    metadata:
      labels:
        app: nodeapi
    spec:
      containers:
      - name: nodeapi
        image: nodejs-api:latest
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapi
  namespace: api-servers
spec:
  type: LoadBalancer
  selector:
    app: nodeapi
  ports:
  - port: 80
    targetPort: 8000
---    
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodeapi
  namespace: api-servers
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodeapi
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
