apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-servers
  namespace: api-servers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapi
  template:
    metadata:
      labels:
        app: nodeapi
    spec:
      containers:
      - name: nodeapi
        image: nodejs-api:latest
      imagePullSecrets:
      - name: docker-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapi
  namespace: api-servers
spec:
  type: NodePort
  selector:
    app: nodeapi
  ports:
  - port: 80
    targetPort: 8000
---    
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodeapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodeapi
  minReplicas: 2
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
